version: '3.12.1'

services:
  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Adjust environment variables as needed

  react:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - django
