# Generated by Django 4.1 on 2024-03-23 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                ("packages", models.TextField(blank=True, null=True)),
                ("drive_type", models.CharField(max_length=50)),
                ("engine", models.CharField(max_length=100)),
                ("color_ext", models.CharField(max_length=50)),
                ("color_int", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("trim", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CarRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mileage", models.IntegerField()),
                ("date", models.DateField(default=datetime.date.today)),
                ("source", models.CharField(max_length=255)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="yellow_rhino.car",
                    ),
                ),
            ],
        ),
    ]
